import textwrap
import unittest

from src.aoc2025.solvers.day07.input_parsing import TachyonManifold, parse_input


class TestInputParsing(unittest.TestCase):

    def test_returns_a_manifold(self):
        the_input = textwrap.dedent(
            """
        .......S.......
        ...............
        .......^.......
        ...............
        ......^.^......
        ..............
        """
        ).strip()

        self.assertIsInstance(parse_input(the_input), TachyonManifold)

    def test_finds_starting_point(self):
        the_input = textwrap.dedent(
            """
        .......S.......
        ...............
        .......^.......
        ...............
        ......^.^......
        ..............
        """
        ).strip()

        manifold = parse_input(the_input)

        self.assertEqual(7, manifold.starting_point)

    def test_finds_splitters(self):
        the_input = textwrap.dedent(
            """
        .......S.......
        ...............
        .......^.......
        ...............
        ......^.^......
        ..............
        """
        ).strip()

        manifold = parse_input(the_input)

        self.assertEqual([set(), {7}, set(), {6, 8}, set()], manifold.splitter_rows)
